# 配置文件

DAILY_TIME: "7:20" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

# 公众号配置
# 公众号appld
"app_id":"wxc49ff0d92aaf18b4",
# 模板消息id
"template_id":"beb5037395da737a53f5673cc61cbba2",
"user":["wyz18297970901"],
"weather_key":"773f355e871e4a1fb307d2d08fdcb952",
"region":"萧山区"
"birthday1":{"name":"梦梦"，"birthday":"1999/12/10"},
"birthday2":{"name":"六六"，"birthday":"2000/6/19"},
"love_date":"2019/04/23"
